<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Implements concrete SqlWebFrontAuthService on CK.DB.Auth.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AspNet.Auth" Version="30.0.1" />
    <PackageReference Include="CK.DB.Auth" Version="28.0.1" />
  </ItemGroup>
</Project>